### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by anindyasarkarIITH** [edouardfouche/neural-based-outlier-discovery#1]
getting the following error while trying to run the code:
TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'
which version of keras are you using?

**Comment by edouardfouche** [comment]
Hi, thank you for reaching out. It seems that keras API has changed a bit. 
The code was running for Keras 1.2.1. An update to the most current version (2.0.4) is planned.

**Comment by edouardfouche** [comment]
I've updated Keras and ran into the same error as you. It seems that you need to update your tensorflow version. The API of tensorflow has changed too and newer versions of Keras adapted to it. Updating tensorflow solved the error. I can confirm that the notebook runs well under the following configuration:
Keras 2.0.4
Tensorflow 1.1.0
